// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var Leaf, LeafParser, Triple;

  exports.Triple = Triple = (function() {
    function Triple(_arg) {
      this.seqno = _arg.seqno, this.payload_hash = _arg.payload_hash, this.sig_id = _arg.sig_id;
    }

    return Triple;

  })();

  LeafParser = (function() {
    function LeafParser(val) {
      this.val = val;
    }

    LeafParser.prototype.parse = function() {
      var version;
      if (!Array.isArray(this.val) || this.val.length < 2) {
        throw new Error("Expected an array of length 2 or more");
      } else if (typeof this.val[0] !== 'number') {
        throw new Error("Need a number for first slot");
      } else if (typeof this.val[1] === 'string') {
        version = 1;
      } else {
        version = this.val[0];
      }
      switch (version) {
        case 1:
          return this.parse_v1();
        case 2:
          return this.parse_v2();
        default:
          throw new Error("unknown leaf version: " + version);
      }
    };

    LeafParser.prototype.parse_v1 = function() {
      var pub;
      pub = this.parse_triple(this.val);
      return new Leaf({
        pub: pub
      });
    };

    LeafParser.prototype.parse_v2 = function() {
      var pub, semipriv, _ref;
      if (this.val.length < 2) {
        throw new Error("No public chain");
      }
      pub = this.parse_triple(this.val[1]);
      semipriv = (this.val.length > 2) && ((_ref = this.val[2]) != null ? _ref.length : void 0) ? this.parse_triple(this.val[2]) : null;
      return new Leaf({
        pub: pub,
        semipriv: semipriv
      });
    };

    LeafParser.prototype.match_hex = function(s) {
      return (typeof s === 'string') && !!(s.match(/^([a-fA-F0-9]*)$/)) && (s.length % 2 === 0);
    };

    LeafParser.prototype.parse_triple = function(val) {
      var msg;
      msg = val.length < 2 ? "Bad triple with < 2 values" : val.length > 3 ? "Bad triple with > 3 values" : typeof val[0] !== 'number' ? "Bad sequence #" : !this.match_hex(val[1]) ? "bad value[1]" : val.length > 2 && val[2].length && !this.match_hex(val[2]) ? "bad value[2]" : null;
      if (msg != null) {
        throw new Error(msg);
      }
      return new Triple({
        seqno: val[0],
        payload_hash: val[1],
        sig_id: val[2]
      });
    };

    return LeafParser;

  })();

  exports.Leaf = Leaf = (function() {
    function Leaf(_arg) {
      this.pub = _arg.pub, this.semipriv = _arg.semipriv;
    }

    Leaf.prototype.get_public = function() {
      return this.pub;
    };

    Leaf.parse = function(version, val) {
      var e, err, leaf, parser;
      parser = new LeafParser(version, val);
      err = leaf = null;
      try {
        leaf = parser.parse();
      } catch (_error) {
        e = _error;
        err = e;
      }
      return [err, leaf];
    };

    return Leaf;

  })();

}).call(this);
