// Generated by IcedCoffeeScript 108.0.13
(function() {
  module.exports = {
    versions: {
      leaf: {
        v1: 1,
        v2: 2
      }
    },
    seqno_types: {
      NONE: 0,
      PUBLIC: 1,
      PRIVATE: 2,
      SEMIPRIVATE: 3
    }
  };

}).call(this);
