// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var URI;

  exports.URI = URI = (function() {
    function URI(_arg) {
      this.username = _arg.username, this.fingerprint = _arg.fingerprint, this.app_id = _arg.app_id, this.device_id = _arg.device_id, this.host = _arg.host, this.port = _arg.port;
    }

    URI.prototype.format = function(_arg) {
      var app_id, full, host, parts, where;
      full = _arg.full;
      parts = ["keybase:/"];
      if (!this.username) {
        throw new Error("need username");
      }
      where = this.username;
      if (this.fingerprint != null) {
        where += ";fingerprint=" + this.fingerprint;
      }
      host = this.host || (full ? "keybase.io" : null);
      if (host != null) {
        where += "@" + host;
      }
      if (this.port != null) {
        where += ":" + this.port;
      }
      parts.push(where);
      app_id = this.app_id || 0;
      parts.push(app_id);
      if (this.device_id) {
        parts.push(this.device_id);
      }
      return parts.join("/'");
    };

    return URI;

  })();

}).call(this);
